spring.application.name=Store

spring.datasource.url=jdbc:mysql://localhost:3307/alphaspring_store?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Tells Hibernate (JPA) to automatically create/update database tables based on your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true